_wandb:
    value:
        cli_version: 0.24.0
        e:
            y4ib9yhbta1gdb13f7mg9erqx7xr2wfi:
                args:
                    - --exp_cfg_path
                    - configs/sam2act_plus.yaml
                    - --mvt_cfg_path
                    - mvt/configs/sam2act_plus.yaml
                    - --mvt_cfg_opts
                    - use_memory True
                    - --exp_cfg_opts
                    - tasks PickXtimes,StopCube,SwingXtimes,BinFill,VideoUnmaskSwap,VideoUnmask,ButtonUnmaskSwap,ButtonUnmask,VideoRepick,VideoPlaceButton,VideoPlaceOrder,PickHighlight,InsertPeg,MoveCube,PatternLock,RouteStick train_iter 800000 epochs 10 bs 20 exp_id sam2act exp_name plus_all_v4
                codePath: sam2act/train_plus.py
                codePathLocal: train_plus.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "21464350720"
                        used: "13147725824"
                email: hongzefu@umich.edu
                executable: /home/hongzefu/micromamba/envs/sam2act/bin/python3.10
                git:
                    commit: bd409f9a132835e57e714b1ae78aaabb52b290e9
                    remote: https://github.com/thomas-fu-0614/sam2act_historybench.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-1be513d6-4652-f4c7-bbc4-71b7f8ad0a17
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-d44e3c3c-fd00-4ecc-7c12-5e5149af6488
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-30b46a3d-dbe7-3ca3-8a6f-f0a364adcb5d
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-92397a00-9620-8712-669b-464b8b836344
                host: gl1528.arc-ts.umich.edu
                memory:
                    total: "540141449216"
                os: Linux-4.18.0-553.85.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /nfs/turbo/coe-chaijy-unreplicated/hongzefu/sam2act_historybench/sam2act/train_plus.py
                python: CPython 3.10.19
                root: /nfs/turbo/coe-chaijy-unreplicated/hongzefu/sam2act_historybench/sam2act
                slurm:
                    cluster_name: greatlakes
                    conf: /var/spool/slurmd.spool/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00030003
                    cpu_bind_list: "0x00030003"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    export_env: ALL
                    get_user_env: "1"
                    gpus_on_node: "4"
                    gpus_per_node: "4"
                    gtids: "0"
                    job_account: chaijy2
                    job_cpus_per_node: "4"
                    job_end_time: "1769728430"
                    job_gid: "114466650"
                    job_gpus: 0,1,2,3
                    job_id: "40980680"
                    job_name: sam2act-plus-binfill
                    job_nodelist: gl1528
                    job_num_nodes: "1"
                    job_partition: spgpu
                    job_qos: normal
                    job_reservation: spgpu_foe_nodes
                    job_start_time: "1769469230"
                    job_uid: "114466650"
                    job_user: hongzefu
                    jobid: "40980680"
                    launch_node_ipaddr: 10.164.10.127
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gl1528
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.164.10.127
                    srun_comm_port: "62845"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "62845"
                    step_nodelist: gl1528
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /nfs/turbo/coe-chaijy-unreplicated/hongzefu
                    submit_host: gl3314.arc-ts.umich.edu
                    task_pid: "956632"
                    tasks_per_node: "1"
                    topology_addr: gl1528
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                    umask: "0002"
                startedAt: "2026-01-26T23:14:28.975703Z"
                writerId: y4ib9yhbta1gdb13f7mg9erqx7xr2wfi
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.57.5
            "12": 0.24.0
            "13": linux-x86_64
agent:
    value: our
bs:
    value: 20
demo:
    value: 100
epochs:
    value: 10
exp_id:
    value: sam2act
exp_name:
    value: plus_all_v4
num_workers:
    value: 5
peract:
    value:
        add_rgc_loss: true
        amp: true
        bnb: true
        lambda_weight_l2: 0.0001
        lr: 0.0001
        lr_cos_dec: true
        num_rotation_classes: 72
        optimizer_type: lamb
        same_trans_aug_per_seq: false
        transform_augmentation: true
        transform_augmentation_rpy:
            - 0
            - 0
            - 45
        transform_augmentation_xyz:
            - 0.125
            - 0.125
            - 0.125
        warmup_steps: 2000
peract_official:
    value:
        cfg_path: configs/peract_official_config.yaml
resume:
    value: ""
rvt:
    value:
        gt_hm_sigma: 1.5
        img_aug: 0
        move_pc_in_bound: true
        place_with_mean: false
sample_distribution_mode:
    value: demo_uniform_temporal
tasks:
    value: PickXtimes,StopCube,SwingXtimes,BinFill,VideoUnmaskSwap,VideoUnmask,ButtonUnmaskSwap,ButtonUnmask,VideoRepick,VideoPlaceButton,VideoPlaceOrder,PickHighlight,InsertPeg,MoveCube,PatternLock,RouteStick
train_iter:
    value: 800000
wandb:
    value: true
